Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  # config.vm.synced_folder "~/Downloads/software", "/software"
  if Vagrant.has_plugin?("vagrant-cachier")
    config.cache.scope = :box
  end
  # single_node
  config.vm.define "single_node" do |single_node|
    single_node.vm.network "private_network", ip: "192.168.100.100"
    single_node.vm.hostname = "singlenode"
    # provision
    single_node.vm.provision :ansible do |ansible|
      ansible.inventory_path = "hosts.yml"
      ansible.verbose = "vv"
      ansible.sudo = true
      ansible.playbook = "playbook.yml"
      ansible.limit = 'hadoop_all'
    end
  end
end
