- name: show return value of command module
  hosts: local
  tasks:
    - name: capture output of id command
      command: id -un
      register: login

    - debug: var=login
    - debug: msg="logged in as user {{ login.stdout }}"
