Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision :shell, inline: "echo abc"
  config.vm.provision :shell, inline: "echo def"
  config.vm.provision :shell, inline: "echo ghi"
end
