Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.provision "shell", path: "script.sh"
  config.vm.provision "chef_solo" do |chef|
    chef.add_recipe "jekyll"
  end
end
