---
# tasks file for mysql

- name: install mysql
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - mysql-server
    - mysql-client
    - python-mysqldb

#- name: copy cnf
#  copy: src=.my.cnf dest=~/.my.cnf owner=ubuntu mode=0644
#  sudo: yes

- name: start mysql service
  sudo: yes
  service: 
    name: mysql 
    state: started
    enabled: true

- name: update mysql root password
  mysql_user:
    name: "{{ user.mysql }}"
    host: "{{ item }}"
    password: "{{ user.mysql_password }}"
    login_user: "{{ user.mysql }}"
    login_password: "{{ user.mysql_password }}"
    check_implicit_admin: yes
    priv: "*.*:ALL,GRANT"
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost

- name: create hive metastore
  mysql_db:
    name: "{{ conf.hive_metastore }}"
    login_user: "{{ user.mysql }}"
    login_password: "{{ user.mysql_password }}"
    state: present

- name: create hive user in mysql
  mysql_user:
    name: "{{ user.hive_mysql }}"
    host: "{{ item }}"
    password: "{{ user.hive_mysql_password }}"
    login_user: "{{ user.mysql }}"
    login_password: "{{ user.mysql_password }}"
    priv: "*.*:ALL,GRANT"
    state: present
  with_items:
    - "{{ ansible_hostname }}"
    - 127.0.0.1
    - ::1
    - localhost
