---
# tasks file for ubuntu

- name: update sources.list
  template: src=sources.list.j2 dest=/etc/apt/sources.list

- name: update cache
  apt: update_cache=yes

- name: install ubuntu packages
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - openjdk-7-jdk
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: disable ipv6 all
  sysctl: name=net.ipv6.conf.all.disable_ipv6 value=1 state=present

- name: disable ipv6 default
  sysctl: name=net.ipv6.conf.default.disable_ipv6 value=1 state=present

- name: disable ipv6 lo
  sysctl: name=net.ipv6.conf.lo.disable_ipv6 value=1 state=present

- name: create the hosts file for all machines
  template: src=etc/hosts.j2 dest=/etc/hosts
