---
# tasks file for ubuntu
- name: update sources.list
  shell: "sed 's@archive.ubuntu.com@mirrors.163.com@' -i /etc/apt/sources.list"
  shell: "sed 's@archive.canonical.com@mirrors.163.com@' -i /etc/apt/sources.list"
  shell: "sed 's@security.ubuntu.com@mirrors.163.com@' -i /etc/apt/sources.list"

- name: update cache
  apt: update_cache=yes

- name: install openjdk-7-jdk
  apt: name=openjdk-7-jdk state=present

- name: copy .bashrc
  copy: src=.bashrc dest=/home/vagrant/.bashrc
