---
# tasks file for ubuntu

- name: update sources.list
  template: src=sources.list.j2 dest=/etc/apt/sources.list

- name: update cache
  apt: update_cache=yes

- name: install ubuntu packages
  apt: name={{ item }} state=present
  sudo: yes
  with_items:
    - openjdk-7-jdk
    - mysql-server
    - mysql-client
    - python-mysqldb

- name: create the hosts file for all machines
  template: src=etc/hosts.j2 dest=/etc/hosts
